"""Research report rendering: model-written markdown -> a self-contained HTML file.

The model never writes HTML. It writes a markdown briefing; this module converts it
with markdown-it in ``js-default`` mode — raw HTML in the (untrusted, web-derived)
briefing is escaped, so a hostile page can skew a summary but cannot inject script
into the report. One file, embedded CSS, no external assets.
"""

from __future__ import annotations

import datetime as _dt
import html
import re
from pathlib import Path

from markdown_it import MarkdownIt

from .tools.web import FetchedPage

_MD = MarkdownIt("js-default")  # html=False: raw HTML from the model/web stays escaped
_SLUG_RE = re.compile(r"[^a-z0-9]+")

_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{
    --bg: #ffffff; --fg: #1a1d21; --muted: #667085; --accent: #0b6e4f;
    --card: #f5f7f9; --border: #e3e8ee;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg: #14171a; --fg: #e6e9ec; --muted: #98a2b3; --accent: #57c297;
      --card: #1d2126; --border: #2c3238;
    }}
  }}
  body {{
    margin: 0 auto; padding: 2.5rem 1.5rem 4rem; max-width: 46rem;
    background: var(--bg); color: var(--fg);
    font: 17px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }}
  header {{ border-bottom: 2px solid var(--accent); margin-bottom: 2rem; }}
  header h1 {{ font-size: 1.7rem; margin: 0 0 .3rem; }}
  header p {{ color: var(--muted); margin: 0 0 1rem; font-size: .9rem; }}
  main h1, main h2 {{ font-size: 1.25rem; margin-top: 2rem; }}
  main h3 {{ font-size: 1.05rem; }}
  a {{ color: var(--accent); }}
  code {{ background: var(--card); padding: .1em .35em; border-radius: 4px; font-size: .9em; }}
  pre {{ background: var(--card); padding: 1rem; border-radius: 8px; overflow-x: auto; }}
  blockquote {{ margin: 0; padding: .2rem 1rem; border-left: 3px solid var(--border);
    color: var(--muted); }}
  .sources {{ margin-top: 3rem; padding: 1.2rem 1.5rem; background: var(--card);
    border: 1px solid var(--border); border-radius: 10px; }}
  .sources h2 {{ margin: 0 0 .8rem; font-size: 1rem; }}
  .sources ol {{ margin: 0; padding-left: 1.4rem; }}
  .sources li {{ margin: .35rem 0; font-size: .92rem; overflow-wrap: anywhere; }}
  .sources .skipped {{ color: var(--muted); }}
  footer {{ margin-top: 3rem; color: var(--muted); font-size: .8rem;
    border-top: 1px solid var(--border); padding-top: 1rem; }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p>research briefing · {date}</p>
</header>
<main>
{body}
</main>
<section class="sources">
  <h2>Sources</h2>
  <ol>
{sources}
  </ol>
{skipped}
</section>
<footer>generated by loon-agent · {model} on {backend} · {date}</footer>
</body>
</html>
"""


def render_report(
    *,
    topic: str,
    briefing_md: str,
    pages: list[FetchedPage],
    failures: list[str] | None = None,
    model: str = "",
    backend: str = "",
) -> str:
    """Render the briefing + numbered source list into a single HTML document."""
    sources = "\n".join(
        f'    <li><a href="{html.escape(page.url, quote=True)}">'
        f"{html.escape(page.title or page.url)}</a></li>"
        for page in pages
    )
    skipped = ""
    if failures:
        items = "".join(f"<li>{html.escape(note)}</li>" for note in failures)
        skipped = (
            '  <p class="skipped">Skipped during the run:</p>\n'
            f'  <ul class="skipped">{items}</ul>'
        )

    return _PAGE.format(
        title=html.escape(topic),
        date=_dt.date.today().isoformat(),
        body=_MD.render(briefing_md),
        sources=sources,
        skipped=skipped,
        model=html.escape(model),
        backend=html.escape(backend),
    )


def write_report(html_text: str, topic: str, reports_dir: Path | str) -> Path:
    """Write the report to ``<reports_dir>/<slug>-<date>.html`` (deduped) and return it."""
    reports_dir = Path(reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)

    slug = _SLUG_RE.sub("-", topic.lower()).strip("-")[:60] or "report"
    stem = f"{slug}-{_dt.date.today().isoformat()}"
    path = reports_dir / f"{stem}.html"
    counter = 2
    while path.exists():
        path = reports_dir / f"{stem}-{counter}.html"
        counter += 1

    path.write_text(html_text, encoding="utf-8")
    return path
